test_suite(
    name = "iOSAppTestSuite2",
    tags = ["manual"],
    tests = [
        "//iOSApp/Test2/ObjCUnitTests:iOSAppObjCUnitTests",
    ],
    visibility = ["@rules_xcodeproj//xcodeproj:generated"],
)
